- name: Deploy to S3
        run: |
          aws s3 sync . s3://mustansar.haseebxbiz.dev \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "infra/*" \
            --delete

      - name: Unlock Public Access and Set Policy
        run: |
          # Step A: Remove the block that prevents public policies
          aws s3api put-public-access-block \
            --bucket mustansar.haseebxbiz.dev \
            --public-access-block-configuration "BlockPublicAcls=false,IgnorePublicAcls=false,BlockPublicPolicy=false,RestrictPublicBuckets=false"
          
          # Step B: Now apply the public read policy
          aws s3api put-bucket-policy --bucket mustansar.haseebxbiz.dev --policy '{
            "Version": "2012-10-17",
            "Statement": [{
              "Sid": "PublicReadGetObject",
              "Effect": "Allow",
              "Principal": "*",
              "Action": "s3:GetObject",
              "Resource": "arn:aws:s3:::mustansar.haseebxbiz.dev/*"
            }]
          }'
